config/routes.rb
Rails.application.routes.draw do
  root :to => 'works#index'

  resources :works do
    post 'rate'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/work.rb
class Work < ActiveRecord::Base
  validates(:artist, :location, :link, :presence => true)
  # before_save(:default_rating)
  # after_create(:default_rating)

  def default_rating
    self.rating = 0
  end

  def rate_post(value)
    if value = '1'
      self.rating = 1
    elsif value = '2'
      self.rating = 2
    elsif value = '3'
      self.rating = 3
    elsif value = '4'
      self.rating = 4
    elsif value = '5'
      self.rating = 5
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    @work.rating = 0
     if @work.save
       redirect_to works_path
     else
       render :new
     end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to works_path
    else
      render :edit
    end
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to works_path
  end

  def rate
    @work = Work.find(params[:work_id])

    if params[:value] === '1'
      puts'YOU GOT 1'
      current_rating = @work.rate_post('1')
      @work.update(rating: current_rating)
      redirect_to works_path
    elsif params[:value] === '2'
      puts'YOU GOT 2'
      current_rating = @work.rate_post('2')
      @work.update(rating: current_rating)
      redirect_to works_path
    elsif params[:value] == '3'
      current_rating = @work.rate_post('3')
      @work.update(rating: current_rating)
      redirect_to works_path
    elsif params[:value] = '4'
      current_rating = @work.rate_post('4')
      @work.update(rating: current_rating)
      redirect_to works_path
    elsif params[:value] = '5'
      current_rating = @work.rate_post('5')
      @work.update(rating: current_rating)
      redirect_to works_path
    end

    # redirect_to works_path
  end

private
  def work_params
    params.require(:work).permit(:artist, :location, :link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @work %>

<%= form_for @work do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/works/edit.html.erb
<h1>Edit <%= @work.artist %> in <%= @work.location %></h1>

<%= render 'layouts/form' %>

<%= link_to "all artists", works_path %>

app/views/works/index.html.erb
<h1>Graffiti Art</h1>

<ul>
  <% @works.each do |work| %>
    <li><%= link_to work.artist, work_path(work) %> - <%= work.location %><br><p>
      rating: <%= work.rating %>/5</p></li>
  <% end %>
</ul>

<hr>
<p><%= link_to "add art", new_work_path %></p>

app/views/works/new.html.erb
<h1>Add Art</h1>

<%= render 'layouts/form' %>

<%= link_to "all artists", works_path %>

app/views/works/show.html.erb
<h1><%= @work.artist %></h1>
<h4>in <%= @work.location %></h4>

<h5><a href="<%= @work.link %>" target="_blank">image</a></h5>
<br>
<p>rate this work</p>
<div class="row">
  <div class="col-sm-1">
    <%= button_to '1', work_rate_path(@work), {:value => '1'} %>
  </div>
  <div class="col-sm-1">
    <%= button_to '2', work_rate_path(@work), {:value => '2'} %>
  </div>
  <div class="col-sm-1">
    <%= button_to '3', work_rate_path(@work), :value => '3' %>
  </div>
  <div class="col-sm-1">
    <%= button_to '4', work_rate_path(@work), :value => '4' %>
  </div>
  <div class="col-sm-1">
    <%= button_to '5', work_rate_path(@work), :value => '5' %>
  </div>
</div>

<br><br>
<%= link_to "Edit", edit_work_path %>
<br>
<%= link_to "Delete", work_path(@work),
                         :data => {:confirm => "Delete this post?",
                                   :method => "delete"} %>

<hr>
<p><%= link_to "all artists", works_path %></p>